### PR TITLE
WIP: 1.3.x patch update TEST WIP 1

### PR DESCRIPTION
**Pull request by brodybits**
_test wip pr to get spec & repo url changes from master to pass AppVeyor CI & Travis CI in 1.3.x branch, apologies for the noise, please ignore_

### CODE REVIEW

**Comment by raphinesse** [comment]
?

**Comment by brodybits** [comment]
Please ignore this, sorry for the bother. Purpose is to get spec updates from master working on 1.3.x, also on the deprecated Node.js 4 version.

**Comment by janpio** [comment]
PRs on own forks don't cause notifications to all the people being subscribed to the main repo ;) (But of course a bit more work...)

**Comment by brodybits** [comment]
Lazy me, moving to personal branch now

**Pull request closed without merging**
