### PR TITLE
CB-13010: Improve logic for searching packages which being installed from git url

### PR DESCRIPTION
**Pull request by matrosov-nikita**
test version: master
steps to reproduce (add twice plugin using git URL):
1) `cordova plugin add https://github.com/AzureAD/azure-activedirectory-library-for-cordova.git`
2) `cordova plugin add https://github.com/AzureAD/azure-activedirectory-library-for-cordova.git`

This PR performs an additional search in destination folder by going through all modules and compare `repository.url` property from `package.json` with target.

### CODE REVIEW

**Comment by audreyso** [comment]
Thank you for this PR. Can you please make sure that an issue was reported on Jira and also include the issue number in your commits. :) 

Example:
Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.

**Comment by matrosov-nikita** [comment]
@audreyso, done. Can you review?

**Comment by filmaj** [comment]
@matrosov-nikita sorry, I am not sure I understand the purpose of this PR. Could you elaborate what you behaviour you are trying to fix or change?

It also looks like this failed the tests on both Windows and Linux. Can you confirm that this fails on your end, locally, too?

**Comment by filmaj** [comment]
OK, I think I see the issue just by trying the repro steps:

```
~/src
➔ cordova create testt
Warning: using prerelease version 7.0.2-dev (cordova-lib@7.0.1)
Creating a new cordova project.

~/src
➔ cd testt

~/src/testt
➔ cordova plugin add https://github.com/AzureAD/azure-activedirectory-library-for-cordova.git
Warning: using prerelease version 7.0.2-dev (cordova-lib@7.0.1)
Adding cordova-plugin-ms-adal to package.json
Saved plugin info for "cordova-plugin-ms-adal" to config.xml

~/src/testt
➔ cordova plugin add https://github.com/AzureAD/azure-activedirectory-library-for-cordova.git
Warning: using prerelease version 7.0.2-dev (cordova-lib@7.0.1)
Error: Failed to fetch plugin https://github.com/AzureAD/azure-activedirectory-library-for-cordova.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

Ping @stevengill for review.

@matrosov-nikita can you also add a unit test for this?

**Comment by stevengill** [comment]
LGTM! A test would be great to have!

**Comment by matrosov-nikita** [comment]
@filmaj, @stevengill, done.

**Comment by stevengill** [comment]
Test failures don't look related to your PR. I'm going to merge this in. Thanks @matrosov-nikita

**Comment by stevengill** [comment]
merged

**Pull request closed without merging**
